"""Ten atomic, positive-polarity items per trait (high P(yes) = more of the trait), for the item-battery reliability test."""
ITEMS = {
 "tech": ["This person is comfortable learning and using new phone apps.", "This person finds new phone apps easy to pick up.", "This person can set up a new smartphone without help.",
          "This person uses online banking or shopping apps regularly.", "This person would try a new app without asking anyone for help.", "This person owns several connected devices such as smart speakers or watches.",
          "This person adapts quickly when an app changes its layout.", "This person uses video calls without difficulty.", "This person is the one family members ask for help with technology.",
          "This person would be comfortable scanning a QR code to sign up for a service."],
 "price": ["This person pays close attention to the cost of small recurring fees.", "This person would drop a service because of a $10 monthly fee.", "This person compares prices before most purchases.",
           "This person keeps track of monthly spending.", "This person cancels subscriptions that are not used often.", "This person waits for sales before buying non-essentials.",
           "This person is worried about unexpected bills.", "This person would choose a cheaper option even if it is less convenient.", "This person reads the price before looking at other details.",
           "This person feels uneasy paying for something that could be done free."],
 "privacy": ["This person is reluctant to give personal details such as an ID or a face photo to a company.", "This person avoids sharing personal data with apps.", "This person declines tracking or cookie requests when possible.",
             "This person would not upload a photo of their government ID to an app.", "This person distrusts companies that store personal data.", "This person adjusts privacy settings on purpose to limit exposure.",
             "This person covers webcams or turns off location sharing.", "This person would refuse a doorbell camera that uploads video to the cloud.", "This person reads privacy settings before signing up for a service.",
             "This person is uncomfortable when a service knows their location."],
 "social": ["This person is at ease meeting and dealing with people they do not know.", "This person often does things together with neighbours or groups.", "This person would happily lend a tool to a neighbour they have not met.",
            "This person enjoys starting conversations with strangers.", "This person goes to community events regularly.", "This person knows many of the people on their street.",
            "This person would join a club of people they have not met.", "This person feels energised after spending time with a group.", "This person is comfortable asking a stranger for help.",
            "This person organises get-togethers for friends or neighbours."],
 "time": ["This person has very little spare time in a typical week.", "This person's days are fully booked.", "This person rarely has an hour free during the working week.",
          "This person often skips things because there is no time.", "This person has caring or work duties that fill most evenings.", "This person feels rushed most days.",
          "This person would struggle to fit a new weekly commitment into their schedule.", "This person eats meals quickly because of time pressure.", "This person has little control over their own schedule.",
          "This person has to plan ahead to find any free time."],
 "novelty": ["This person likes to try new products soon after they appear.", "This person tries new products soon after they are released.", "This person gets bored with routine.",
             "This person enjoys visiting places they have never been.", "This person is among the first of their friends to try a new service.", "This person switches brands to try something different.",
             "This person likes unfamiliar foods and experiences.", "This person welcomes changes in their routine.", "This person seeks out new ideas and hobbies.",
             "This person would try a product that few other people have used."],
}
