DIALS = ["prices", "job_security", "safety_fear", "health_risk", "trust_institutions", "community", "tech_pace", "disruption", "optimism"]
Q = {  # (dial, +1 up / -1 down) -> four yes/no questions. 'up' = more of the dial name.
 ("prices", 1): ["This story reports that the prices of everyday goods or services have gone up.", "This story reports that households are paying more for the same things.", "This story reports inflation or the cost of living rising.", "This story reports a price increase that affects ordinary consumers."],
 ("prices", -1): ["This story reports that the prices of everyday goods or services have gone down.", "This story reports that households are paying less for the same things.", "This story reports inflation easing or prices falling.", "This story reports a price cut that benefits ordinary consumers."],
 ("job_security", 1): ["This story reports hiring or job creation.", "This story reports unemployment falling.", "This story reports a company expanding its workforce.", "This story reports job openings or wages rising."],
 ("job_security", -1): ["This story reports layoffs or job losses.", "This story reports unemployment rising.", "This story reports a company closing or cutting staff.", "This story reports workers who are worried about losing their jobs."],
 ("safety_fear", 1): ["This story reports a violent crime or attack.", "This story reports crime rising.", "This story reports people feeling unsafe.", "This story reports a threat to public safety."],
 ("safety_fear", -1): ["This story reports crime falling.", "This story reports a public safety threat ending or being resolved.", "This story reports neighbourhoods becoming safer.", "This story reports a reduction in violence."],
 ("health_risk", 1): ["This story reports a disease outbreak or spread.", "This story reports hospitals under strain.", "This story reports a health warning to the public.", "This story reports rising illness or infections."],
 ("health_risk", -1): ["This story reports an outbreak ending or declining.", "This story reports a successful vaccine or treatment rollout.", "This story reports illness rates falling.", "This story reports hospitals returning to normal capacity."],
 ("trust_institutions", 1): ["This story reports an institution such as a government, company or media outlet acting credibly or honestly.", "This story reports public approval of an institution rising.", "This story reports a successful reform or accountability measure.", "This story reports an institution being open and transparent."],
 ("trust_institutions", -1): ["This story reports a scandal or corruption involving an institution.", "This story reports an institution misleading or hiding information from the public.", "This story reports public trust in an institution falling.", "This story reports an official resigning over misconduct."],
 ("community", 1): ["This story reports neighbours or volunteers helping each other.", "This story reports a surge in volunteering or donations.", "This story reports a community coming together.", "This story reports a new community space or event bringing people together."],
 ("community", -1): ["This story reports a community divided or in conflict.", "This story reports community services or gathering places closing.", "This story reports rising loneliness or isolation.", "This story reports neighbours in dispute."],
 ("tech_pace", 1): ["This story reports a major new technology launch or breakthrough.", "This story reports rapid adoption of a new technology.", "This story reports a new technology changing how people work or live.", "This story reports a company releasing a much more capable product."],
 ("tech_pace", -1): ["This story reports a technology rollout being delayed or cancelled.", "This story reports a regulation restricting a technology.", "This story reports adoption of a technology slowing.", "This story reports a technology failing or being withdrawn."],
 ("disruption", 1): ["This story reports services or travel being interrupted.", "This story reports severe weather affecting daily life.", "This story reports a strike, outage or shutdown.", "This story reports people unable to follow their usual routines."],
 ("disruption", -1): ["This story reports services being restored.", "This story reports normal operations resuming after an interruption.", "This story reports transport or power back to normal.", "This story reports an end to a strike or outage."],
 ("optimism", 1): ["This story reports rising confidence about the future.", "This story reports people or businesses feeling more hopeful.", "This story reports surveys showing improved sentiment.", "This story reports good news that people say lifts their mood."],
 ("optimism", -1): ["This story reports falling confidence about the future.", "This story reports people feeling pessimistic.", "This story reports surveys showing worsening sentiment.", "This story reports bad news that people say weighs on their mood."],
}
TYPE_Q = {"happened": "This story reports something that has already happened.", "opinion": "This story is mainly an opinion or commentary.", "forecast": "This story is mainly a forecast or prediction about the future."}
D = lambda t, *exp: ("dial", t, dict(exp))
H = [  # (kind, text, expected {dial: +1/-1}) ; ambiguous: expected = {contested dial: 0}
("dial", "Grocery prices jump 8% in a year. Shoppers say a typical weekly shop now costs noticeably more than last year, according to new official figures.", {"prices": 1}),
("dial", "Rent increases accelerate in major cities. Landlords raised rents by an average of 9%, leaving many tenants paying hundreds more each month.", {"prices": 1}),
("dial", "Petrol prices fall for the fifth straight week. Drivers are paying about 20 cents less per litre than a month ago as crude oil costs ease.", {"prices": -1}),
("dial", "Supermarket chain cuts prices on 2,000 basic items. Staples such as bread, milk and eggs will cost less starting Monday, the company announced.", {"prices": -1}),
("dial", "Auto maker to cut 4,000 jobs at two plants. The company said the layoffs will begin next month as demand for its vehicles weakens.", {"job_security": -1}),
("dial", "Unemployment rises to its highest level in three years. The jobless rate climbed to 6.1% as employers across several sectors reduced staff.", {"job_security": -1}),
("dial", "Hospital system to hire 1,500 nurses and technicians. The expansion will create permanent positions across five regional sites by the end of the year.", {"job_security": 1}),
("dial", "Unemployment falls to a record low. The jobless rate dropped to 3.4% as employers added 250,000 positions last month.", {"job_security": 1}),
("dial", "Shooting at downtown market leaves three dead. Police said a gunman opened fire on shoppers on Saturday and remains at large.", {"safety_fear": 1}),
("dial", "Burglaries and car thefts surge across the suburbs. Police report a 30% rise in property crime this year, and residents say they no longer feel safe at night.", {"safety_fear": 1}),
("dial", "Violent crime falls to the lowest level in a decade. City police said fewer assaults and robberies were reported than at any point since 2014.", {"safety_fear": -1}),
("dial", "Gunman arrested after a week-long manhunt. Police said the area is now safe and residents can return to normal life.", {"safety_fear": -1}),
("dial", "Measles outbreak spreads to six counties. Health officials reported 140 new cases this week and urged unvaccinated families to take precautions.", {"health_risk": 1}),
("dial", "Hospitals report emergency rooms at capacity as flu cases surge. Several facilities are turning patients away as infections climb sharply.", {"health_risk": 1}),
("dial", "Health officials declare the outbreak over. No new cases have been reported in six weeks, the department said Tuesday.", {"health_risk": -1}),
("dial", "Vaccination campaign reaches 90% of the target group. Hospital admissions have dropped sharply and doctors say illness rates are falling.", {"health_risk": -1}),
("dial", "Mayor resigns amid corruption investigation. Prosecutors say city contracts were awarded to friends of the mayor in exchange for payments.", {"trust_institutions": -1}),
("dial", "Regulator found to have hidden safety reports from the public. An inquiry found the agency withheld warnings for two years, and public approval has plunged.", {"trust_institutions": -1}),
("dial", "Independent audit clears city of wrongdoing and praises transparency. The report found the council handled public funds honestly and published its accounts in full.", {"trust_institutions": 1}),
("dial", "Public approval of the health agency rises to 78%. Survey respondents credited its clear and honest communication during the winter crisis.", {"trust_institutions": 1}),
("dial", "Neighbours rally to rebuild family's home after fire. Hundreds of volunteers donated materials and spent the weekend helping.", {"community": 1}),
("dial", "Record number of residents sign up to volunteer at food banks. Organisers say communities are coming together to support those in need.", {"community": 1}),
("dial", "Library and community centre to close in budget cuts. The closures remove the last free gathering places in the neighbourhood.", {"community": -1}),
("dial", "Survey finds record share of adults report feeling lonely. Researchers say fewer people know their neighbours and community clubs are shrinking.", {"community": -1}),
("dial", "Company unveils assistant that can handle customer calls end to end. Early users say the system replaces most routine support tasks.", {"tech_pace": 1}),
("dial", "Electric vehicle sales double as new fast-charging network opens. Analysts say adoption is moving much faster than expected.", {"tech_pace": 1}),
("dial", "Regulators halt rollout of self-driving taxis after safety concerns. The service was suspended in all cities pending review.", {"tech_pace": -1}),
("dial", "Smart home maker withdraws its flagship device after repeated failures. The company said the product will not return to shelves.", {"tech_pace": -1}),
("dial", "Blizzard shuts down highways and cancels hundreds of flights. Schools and offices closed across the region as snow continued to fall.", {"disruption": 1}),
("dial", "Rail strike halts commuter trains for a third day. Millions of workers have been unable to travel to their jobs.", {"disruption": 1}),
("dial", "Power fully restored after four-day outage. Utilities said all customers are back online and traffic lights are working again.", {"disruption": -1}),
("dial", "Strike ends and trains resume normal schedules. Commuters returned to regular timetables on Monday morning.", {"disruption": -1}),
("dial", "Consumer confidence jumps to a three-year high. A survey found more households feel hopeful about the year ahead.", {"optimism": 1}),
("dial", "Poll: most young people say they expect their lives to improve. Respondents described feeling more optimistic than at any time since the survey began.", {"optimism": 1}),
("dial", "Consumer confidence plunges to its lowest level in a decade. Surveys show households increasingly pessimistic about the year ahead.", {"optimism": -1}),
("dial", "Poll finds most adults expect their children to be worse off. Respondents said they feel discouraged about the future.", {"optimism": -1}),
] + [("irrelevant", t, {}) for t in [
"Local team wins the championship in overtime. Fans celebrated into the night after a last-second goal.", "Singer announces world tour with 40 dates. Tickets go on sale Friday for the performances starting in spring.",
"Zoo welcomes a baby giraffe. The calf was born on Tuesday and is nursing well, keepers said.", "Chef opens new restaurant specialising in regional seafood. The menu changes weekly based on the catch.",
"Film about a lighthouse keeper wins top prize at festival. The director thanked the cast in a short speech.", "Astronomers photograph a distant galaxy cluster. The image shows light that left the cluster billions of years ago.",
"Museum extends opening hours for its dinosaur exhibition. Visitors can now see the fossils until nine in the evening.", "Tennis star advances to semi-finals with straight-sets win. She will face the defending champion on Saturday.",
"Bakery wins award for best sourdough in the region. The owner said the recipe has not changed in thirty years.", "Orchestra to perform all nine symphonies in one weekend. The conductor said it will be a demanding programme.",
"New species of frog discovered in mountain forest. Researchers found the small green frog during a night survey.", "Gardening club holds annual flower show. Prizes were awarded for roses, dahlias and the largest marrow.",
"Author's new novel tops the bestseller list. The book follows three generations of a fishing family.", "Chess champion defends title in dramatic final game. The match lasted seven hours.",
"City marathon draws record number of runners. Organisers said 30,000 people took part on a sunny morning.", "Famous painting returns to gallery after restoration. Conservators spent two years cleaning and repairing the canvas.",
"Astronaut shares photographs from orbit. The images show the coastline at night.", "Local school's choir wins national competition. The pupils performed a folk song in three-part harmony.",
"Theatre announces its next season of plays. The programme includes two comedies and a new historical drama.", "Scientists identify the oldest known fossil forest. The trees grew nearly 400 million years ago."]
] + [("opinion", t, {}) for t in [
"Opinion: Rising prices are a disgrace and the government should be ashamed. The columnist argues households deserve better.", "Commentary: Why layoffs are the fault of greedy executives. The writer says workers have been betrayed.",
"Opinion: Our streets are not safe and politicians refuse to admit it. The author calls for tougher action.", "Column: The health system is failing us all. The writer says the public is being let down.",
"Opinion: We can no longer trust the media or the government. The author says honesty has vanished from public life.", "Commentary: Communities are falling apart and nobody cares. The columnist laments the loss of neighbourliness.",
"Opinion: Technology is moving too fast and we should slow down. The writer argues society cannot keep up.", "Column: Why the winter storms were an overreaction by authorities. The writer says closures were unnecessary.",
"Opinion: Young people have every reason to be hopeful. The columnist argues the future is brighter than the headlines suggest.", "Commentary: Why cheap goods are a myth. The author argues shoppers are being fooled by sales."]
] + [("forecast", t, {}) for t in [
"Economists predict prices will rise sharply next year. Analysts expect inflation to reach 9% by spring.", "Report forecasts 100,000 job losses by next summer. Analysts warn that automation could eliminate many roles.",
"Police chief warns crime could surge if funding is cut. The chief said violence may rise in coming months.", "Experts expect a severe flu season. Forecasters say hospitals may be overwhelmed by winter.",
"Analysts predict consumer confidence will collapse. The next survey is expected to show a record drop.", "Forecasters say a major storm could hit the coast next week. Authorities may order closures if the storm arrives.",
"Researchers predict rapid adoption of voice assistants. Analysts say most homes will have one within five years.", "Strike likely next month, union leaders warn. Talks could collapse by the end of the week.",
"Pollsters expect trust in the government to fall further. Analysts say upcoming scandals may deepen distrust.", "Charity predicts record volunteering this winter. Organisers say they expect more people to help."]
] + [("ambiguous", t, {c: 0}) for t, c in [
("Prices rise 5% but wages rise 7%. Households say they feel better off despite the higher bills.", "prices"), ("Factory closes but a new warehouse opens nearby. The plant cut 500 jobs while the warehouse will hire 450.", "job_security"),
("Crime in the north falls while the south sees a spike. Police said totals are unchanged overall.", "safety_fear"), ("New vaccine reduces cases but side effects reported. Health officials say infections fell while some patients felt ill.", "health_risk"),
("Mayor survives vote of confidence despite fraud allegations. Supporters praise her record while critics demand an inquiry.", "trust_institutions"), ("Community centre closes but residents open a volunteer-run replacement. The council withdrew funds but neighbours took over.", "community"),
("Self-driving trial is paused after one incident but expands in two other cities. Regulators said results are mixed.", "tech_pace"), ("Storm closes ports but trains run normally. Services were disrupted in some areas and unaffected in others.", "disruption"),
("Sentiment survey shows households split. Half say they feel more hopeful and half feel more worried.", "optimism"), ("Fuel prices fall while food prices climb. Analysts said average costs were broadly unchanged.", "prices")]
] + [("multi", t, e) for t, e in [
("Hurricane makes landfall, thousands evacuated. Power is out across the coast and hospitals are treating the injured.", {"disruption": 1, "health_risk": 1, "safety_fear": 1}),
("Factory shutdown leaves 3,000 jobless as prices rise. The town faces layoffs while local shop prices climb.", {"job_security": -1, "prices": 1}),
("Cyberattack on bank locks millions out of accounts. The institution has not explained what happened and customers are furious.", {"disruption": 1, "trust_institutions": -1}),
("Pandemic lockdown closes schools and shops. Officials say cases are rising and people are told to stay at home.", {"health_risk": 1, "disruption": 1}),
("Wildfire destroys 200 homes; neighbours open their doors to evacuees. Volunteers have collected food and clothing.", {"disruption": 1, "community": 1}),
("Scandal at the health agency as outbreak spreads. Officials are accused of covering up case numbers while infections rise.", {"trust_institutions": -1, "health_risk": 1}),
("Recovery: economy adds jobs and prices fall. Unemployment falls to 4% while inflation eases to 2%.", {"job_security": 1, "prices": -1}),
("Riots break out after police shooting; curfew imposed. Shops are shuttered and residents stay indoors.", {"safety_fear": 1, "disruption": 1}),
("New AI tools replace thousands of office jobs. Companies announce layoffs as automation spreads quickly.", {"tech_pace": 1, "job_security": -1}),
("Heatwave kills dozens and knocks out power. Hospitals report overflowing emergency rooms.", {"health_risk": 1, "disruption": 1}),
("Services restored and crime falls after the festival ends. Authorities said the city is back to normal.", {"disruption": -1, "safety_fear": -1}),
("Trust in banks falls as lenders raise fees. Customers say they pay more and feel misled.", {"trust_institutions": -1, "prices": 1}),
("Hopeful survey as hiring picks up. Households report feeling more confident as unemployment falls.", {"optimism": 1, "job_security": 1}),
("Vaccine success lifts mood and reopens schools. Cases drop and parents say they feel relieved.", {"health_risk": -1, "optimism": 1, "disruption": -1})]]
assert len(H) == 100, len(H)
