/* Invented, illustrative scripts. Nothing here is a real call, and every tag is a scripted MOCK annotation, not model output.
   The real-transcript scenario lives in apollo.js. */
window.MockScenarios = [
{ id: "meeting", kind: "invented", title: "Vendor review meeting (invented script)",
  blurb: "Invented script for layout only. Four people, a contract renewal, a few sensitive moments.",
  watch: [
    { code: "NUM", label: "Figures", prompt: "Any price, budget or quantity that is stated", hue: 205 },
    { code: "CMT", label: "Commitments", prompt: "Someone promises something, especially with a date", hue: 150 },
    { code: "EVA", label: "Evasion", prompt: "A direct question is dodged or answered with something else", hue: 48 },
    { code: "PRS", label: "Pressure", prompt: "The speaker pushes the other side with urgency or a threat", hue: 350 },
    { code: "CON", label: "Confidential", prompt: "Information that sounds internal or not meant to be shared", hue: 275 } ],
  turns: [
    { speaker: "Dana (Buyer)", text: "Thanks for joining. We want to settle the renewal today if we can." },
    { speaker: "Marco (Vendor)", text: "Happy to. The current plan runs at 118 thousand a year, and we can hold that for another term." },
    { speaker: "Dana (Buyer)", text: "Your competitor quoted us 92 thousand. Can you explain the gap?" },
    { speaker: "Marco (Vendor)", text: "Well, every platform is different, and we really value the relationship we have built together." },
    { speaker: "Dana (Buyer)", text: "That doesn't answer the price. What is the gap made of?" },
    { speaker: "Priya (Vendor)", text: "Between us, the internal cost target for this account is about 85, so there is room to move." },
    { speaker: "Marco (Vendor)", text: "Priya, let's keep that off the record. What I can say is this offer expires on Friday." },
    { speaker: "Dana (Buyer)", text: "If it expires Friday I need it in writing today, otherwise we walk." },
    { speaker: "Marco (Vendor)", text: "I will send the revised terms by five o'clock today, and I promise a discount of ten percent." },
    { speaker: "Sam (Buyer)", text: "Legal still has to review the data clause, so we cannot sign before the twentieth." } ],
  marks: [
    { turn: 1, phrase: "118 thousand a year", code: "NUM", p: 0.94, note: "Current price 118k per year", fact: ["Current price", "118k / year"] },
    { turn: 2, phrase: "92 thousand", code: "NUM", p: 0.92, note: "Competitor quote 92k", fact: ["Competitor quote", "92k"] },
    { turn: 3, phrase: "we really value the relationship", code: "EVA", p: 0.81, note: "Price question answered with relationship talk" },
    { turn: 4, phrase: "That doesn't answer the price", code: "EVA", p: 0.62, note: "Buyer flags the dodge" },
    { turn: 5, phrase: "Between us, the internal cost target", code: "CON", p: 0.9, note: "Internal cost target disclosed", fact: ["Vendor floor (leaked)", "about 85k"] },
    { turn: 6, phrase: "keep that off the record", code: "CON", p: 0.85, note: "Speaker tries to retract the disclosure" },
    { turn: 6, phrase: "this offer expires on Friday", code: "PRS", p: 0.83, note: "Deadline pressure" },
    { turn: 7, phrase: "otherwise we walk", code: "PRS", p: 0.72, note: "Counter-pressure" },
    { turn: 8, phrase: "by five o'clock today", code: "CMT", p: 0.9, note: "Promise with a time", fact: ["Promise", "Revised terms by 17:00 today"] },
    { turn: 8, phrase: "discount of ten percent", code: "NUM", p: 0.88, note: "10% discount", fact: ["Discount promised", "10%"] },
    { turn: 9, phrase: "cannot sign before the twentieth", code: "CMT", p: 0.78, note: "Signing blocked until the 20th", fact: ["Earliest signature", "the 20th (legal review)"] } ] },

{ id: "sales", kind: "invented", title: "Sales discovery call (invented script)",
  blurb: "Invented script for layout only. A rep and a prospect; the useful signals are buying intent, objections and competitors.",
  watch: [
    { code: "BUY", label: "Buying signal", prompt: "The prospect sounds ready to move forward", hue: 150 },
    { code: "OBJ", label: "Objection", prompt: "The prospect raises a concern or a reason to hold back", hue: 350 },
    { code: "CMP", label: "Competitor", prompt: "A competing product or vendor is mentioned", hue: 275 },
    { code: "PRC", label: "Pricing", prompt: "Budget, price or discount is discussed", hue: 205 },
    { code: "DEC", label: "Decision maker", prompt: "Someone who signs or blocks the deal is named", hue: 48 } ],
  turns: [
    { speaker: "Rep", text: "Tell me what is slowing your team down at the moment." },
    { speaker: "Prospect", text: "Honestly, reporting. My analysts spend two days a week stitching spreadsheets together." },
    { speaker: "Rep", text: "That is common. Have you looked at anything to fix it?" },
    { speaker: "Prospect", text: "We trialled Northwind last quarter, but the setup was painful and we dropped it." },
    { speaker: "Rep", text: "Understood. If we could get you live in a week, would that change things?" },
    { speaker: "Prospect", text: "It would. Our budget is around forty thousand, and I would need to move fast before the quarter closes." },
    { speaker: "Rep", text: "That fits. Who else needs to be involved in the decision?" },
    { speaker: "Prospect", text: "My VP, Elena Ruiz, signs anything over twenty five thousand. She is skeptical of new vendors." },
    { speaker: "Rep", text: "Could we get her on a call this week?" },
    { speaker: "Prospect", text: "Send me a one-pager and I will try to get her ten minutes on Thursday." } ],
  marks: [
    { turn: 1, phrase: "two days a week", code: "OBJ", p: 0.6, note: "Pain point, not an objection: the cost of the status quo", fact: ["Pain", "Two analyst-days per week on reporting"] },
    { turn: 3, phrase: "We trialled Northwind", code: "CMP", p: 0.93, note: "Competitor trialled", fact: ["Competitor", "Northwind (dropped: painful setup)"] },
    { turn: 3, phrase: "the setup was painful", code: "OBJ", p: 0.84, note: "Past objection: setup effort" },
    { turn: 5, phrase: "It would", code: "BUY", p: 0.82, note: "Positive response to one-week go-live" },
    { turn: 5, phrase: "budget is around forty thousand", code: "PRC", p: 0.95, note: "Budget stated", fact: ["Budget", "about 40k"] },
    { turn: 5, phrase: "move fast before the quarter closes", code: "BUY", p: 0.88, note: "Time pressure on their side", fact: ["Deadline", "end of quarter"] },
    { turn: 7, phrase: "Elena Ruiz, signs anything over twenty five thousand", code: "DEC", p: 0.94, note: "Signer identified", fact: ["Signer", "Elena Ruiz, VP (over 25k)"] },
    { turn: 7, phrase: "skeptical of new vendors", code: "OBJ", p: 0.86, note: "Upcoming objection from the signer" },
    { turn: 9, phrase: "get her ten minutes on Thursday", code: "BUY", p: 0.9, note: "Concrete next step", fact: ["Next step", "10 min with VP, Thursday"] } ] },

{ id: "dispatch", kind: "invented", title: "Emergency call, structured intake (invented script)",
  blurb: "Invented script for layout only. Not a real call. The point is how hidden details (place, injuries, hazards) get pulled out while the caller is still talking.",
  watch: [
    { code: "LOC", label: "Location", prompt: "An address, street, landmark or place is given", hue: 205 },
    { code: "INJ", label: "Injury", prompt: "Someone is hurt, unconscious or not breathing", hue: 350 },
    { code: "HAZ", label: "Hazard", prompt: "Fire, gas, weapons, traffic or any ongoing danger", hue: 18 },
    { code: "PPL", label: "People", prompt: "How many people are involved, including children", hue: 150 },
    { code: "DIS", label: "Distress", prompt: "The caller is panicking or losing control", hue: 275 } ],
  turns: [
    { speaker: "Dispatcher", text: "Emergency services, what is the address of the emergency?" },
    { speaker: "Caller", text: "Please hurry, it's 42 Alder Court, the kitchen is on fire and I can't get to my dad!" },
    { speaker: "Dispatcher", text: "Stay on the line. Is your father breathing?" },
    { speaker: "Caller", text: "I don't know, he's on the floor, he isn't answering me, oh my god." },
    { speaker: "Dispatcher", text: "Are there other people in the house?" },
    { speaker: "Caller", text: "My two kids are upstairs, they are six and nine. There is a gas stove, I can smell gas." },
    { speaker: "Dispatcher", text: "Get the children out of the house now and do not use any switches." },
    { speaker: "Caller", text: "Okay, okay, we are going out the front door." },
    { speaker: "Dispatcher", text: "Good. Units are on the way. Stay outside and away from the building." } ],
  marks: [
    { turn: 1, phrase: "42 Alder Court", code: "LOC", p: 0.97, note: "Address", fact: ["Address", "42 Alder Court"] },
    { turn: 1, phrase: "the kitchen is on fire", code: "HAZ", p: 0.95, note: "Fire in kitchen", fact: ["Hazard", "Kitchen fire"] },
    { turn: 1, phrase: "Please hurry", code: "DIS", p: 0.8, note: "Urgent, distressed" },
    { turn: 3, phrase: "he's on the floor, he isn't answering", code: "INJ", p: 0.9, note: "Adult unresponsive", fact: ["Patient", "Father, unresponsive, breathing unknown"] },
    { turn: 3, phrase: "oh my god", code: "DIS", p: 0.86, note: "Rising distress" },
    { turn: 5, phrase: "My two kids are upstairs, they are six and nine", code: "PPL", p: 0.93, note: "Two children upstairs", fact: ["Children", "2 (ages 6 and 9), upstairs"] },
    { turn: 5, phrase: "I can smell gas", code: "HAZ", p: 0.96, note: "Gas leak risk: explosion", fact: ["Hazard", "Kitchen fire + gas smell"] },
    { turn: 7, phrase: "we are going out the front door", code: "PPL", p: 0.7, note: "Group evacuating", fact: ["Status", "Caller and children leaving by front door"] } ] },

{ id: "callcenter", kind: "invented", title: "Customer support, escalating call (invented script)",
  blurb: "Invented script for layout only. Shows how anger, cancel intent and account details surface in the margin.",
  watch: [
    { code: "ANG", label: "Anger", prompt: "The customer is angry or hostile", hue: 350 },
    { code: "CXL", label: "Cancel intent", prompt: "The customer says they may cancel or leave", hue: 18 },
    { code: "PII", label: "Personal data", prompt: "Account numbers, addresses, card or ID details are spoken", hue: 275 },
    { code: "LEG", label: "Legal threat", prompt: "Lawyer, regulator, chargeback or public complaint is mentioned", hue: 48 },
    { code: "SAT", label: "Recovery", prompt: "The customer softens or accepts an offer", hue: 150 } ],
  turns: [
    { speaker: "Agent", text: "Thanks for calling, how can I help today?" },
    { speaker: "Customer", text: "This is the third time I am calling about the same double charge, and nobody has fixed it." },
    { speaker: "Agent", text: "I am sorry about that. Can I have your account number?" },
    { speaker: "Customer", text: "It's 5 5 0 1 8 8 2, and honestly this is ridiculous." },
    { speaker: "Agent", text: "Thank you. I can see two charges of 79 dollars on the fourth." },
    { speaker: "Customer", text: "Yes! If it is not refunded today I am cancelling and I will dispute it with my bank." },
    { speaker: "Agent", text: "I can refund one charge now and the second within two days, and add a month free." },
    { speaker: "Customer", text: "Fine. That is fair, thank you for actually listening." } ],
  marks: [
    { turn: 1, phrase: "third time I am calling", code: "ANG", p: 0.78, note: "Repeat contact, frustration" },
    { turn: 3, phrase: "5 5 0 1 8 8 2", code: "PII", p: 0.93, note: "Account number spoken aloud", fact: ["Account", "5501882 (masked in log)"] },
    { turn: 3, phrase: "this is ridiculous", code: "ANG", p: 0.86, note: "Anger rising" },
    { turn: 4, phrase: "two charges of 79 dollars", code: "PII", p: 0.55, note: "Billing detail", fact: ["Issue", "Duplicate 79 USD charge on the 4th"] },
    { turn: 5, phrase: "I am cancelling", code: "CXL", p: 0.92, note: "Explicit cancel threat", fact: ["Churn risk", "High: will cancel if not refunded today"] },
    { turn: 5, phrase: "dispute it with my bank", code: "LEG", p: 0.88, note: "Chargeback threat" },
    { turn: 6, phrase: "add a month free", code: "SAT", p: 0.6, note: "Offer made" },
    { turn: 7, phrase: "That is fair, thank you", code: "SAT", p: 0.94, note: "Customer accepts, tone softens" } ] }
];
