"""Structured world population: drawn from data/countries.csv (country parameters) with fixed rules. Same person layers as the single-country population, plus country, settlement and sampling weight.
Everything here is simulated start data (illustrative parameters), generated by rules; nothing is typed in by hand per person."""
import csv, numpy as np
D = "/workspace/probes/world-engine/data"
NUM = ["pop_m", "median_age", "income_k", "urban", "tech", "privacy", "social", "time", "novelty", "price"]
def load_countries():
    rows = list(csv.DictReader(open(f"{D}/countries.csv")))
    for r in rows:
        for k in r:
            if k not in ("id", "name", "source"): r[k] = float(r[k])
    return rows
HH = ["lives alone", "lives with a partner", "lives with a partner and children", "lives with housemates", "lives with parents", "lives with an adult child"]
class WorldPopulation:
    def __init__(self, n_per=12500, seed=1):
        r = np.random.default_rng(seed); self.countries = cs = load_countries(); cols = {k: [] for k in ("country", "settle", "age", "inc", "area", "household", "work", "caregiver", "tech", "price", "privacy", "social", "time", "novelty", "wt")}
        for ci, c in enumerate(cs):
            n = n_per; adult_med = c["median_age"] + 8; age = np.clip(18 + r.gamma(2.0, (adult_med - 18) / 1.678, n), 18, 90)
            ik = c["income_k"] * np.exp(0.85 * r.standard_normal(n)) * (1 - 0.0008 * (age - 45) ** 2).clip(0.4, 1.1); inc = np.digitize(ik, [30, 60, 100])
            u = r.random(n); urb = c["urban"]; area = np.where(u < urb * 0.55, "large city", np.where(u < urb, "suburb", np.where(u < urb + (1 - urb) * 0.4, "small town", "rural area"))); settle = np.where(np.isin(area, ["large city", "suburb"]), 0, np.where(area == "small town", 1, 2))
            fert = np.clip((40 - c["median_age"]) / 25, 0.2, 1.0); P = np.zeros((n, 6))
            young, mid, old = age < 30, (age >= 30) & (age < 60), age >= 60
            P[young] = [.12, .23, .12 + .2 * fert, .20, .25, 0]; P[mid] = [.15, .25, .15 + .5 * fert, .10, .0, .05]; P[old] = [.30, .40, 0, 0, 0, .30 * (1 - 0.3 * fert)]
            P /= P.sum(1, keepdims=True); hh = np.array(HH)[(r.random(n)[:, None] > np.cumsum(P, 1)).sum(1).clip(0, 5)]
            work = np.where((age >= 65) & (r.random(n) < 0.7 - 0.4 * fert), "retired", "working"); cg = r.random(n) < np.where((age >= 40) & (age <= 70), .28, .05)
            kids = np.char.find(hh, "children") >= 0; alone = hh == "lives alone"; rural = np.isin(area, ["small town", "rural area"]); retired = work == "retired"
            cl = lambda x: np.clip(x, 1, 5)
            cols["tech"].append(cl(c["tech"] - (age - 40) / 22 + 0.15 * (inc - 1.5) + 0.9 * r.standard_normal(n))); cols["price"].append(cl(c["price"] + (1.5 - inc) * 0.45 + 0.8 * r.standard_normal(n)))
            cols["privacy"].append(cl(c["privacy"] + (age - 47) / 40 + 1.0 * r.standard_normal(n))); cols["social"].append(cl(c["social"] + 0.5 * rural - 0.4 * alone + 1.0 * r.standard_normal(n)))
            cols["time"].append(cl(c["time"] - 0.6 + 1.4 * kids + 1.0 * cg - 1.0 * retired + 0.8 * r.standard_normal(n))); cols["novelty"].append(cl(c["novelty"] + 1.0 - (age - 18) / 25 + 1.0 * r.standard_normal(n)))
            for k, v in (("country", np.full(n, ci)), ("settle", settle), ("age", age), ("inc", inc), ("area", area), ("household", hh), ("work", work), ("caregiver", cg), ("wt", np.full(n, c["pop_m"] / n))): cols[k].append(v)
        for k in cols: setattr(self, k, np.concatenate(cols[k]))
        self.n = len(self.age); self.wt = self.wt / self.wt.sum(); self.region = self.country * 3 + self.settle; rr = np.random.default_rng(seed + 99); cl = lambda x: np.clip(x, 1, 5); inc, age, n = self.inc, self.age, self.n
        col = {"tech_comfort": self.tech, "price_attention": self.price, "privacy_stance": self.privacy, "social_ease": self.social, "time_pressure": self.time, "novelty_seeking": self.novelty, "financial_stress": 1 + 0.5 * (3 - inc),
               "optimism": cl(3 + .6 * rr.standard_normal(n)), "safety_concern": cl(3 + .7 * rr.standard_normal(n)), "institutional_trust": cl(3 + .7 * rr.standard_normal(n)), "liquidity": cl(1 + .9 * inc + (age >= 60) * .5 + .5 * rr.standard_normal(n)),
               "habit_inertia": cl(2.2 + age / 50 + .6 * rr.standard_normal(n)), "loss_aversion": cl(3 + .6 * rr.standard_normal(n)), "tenure": np.full(n, 3.0), "life_stage": 1 + 4 * age / 90}
        import engine as E
        self.base = np.column_stack([col[e] for e in E.ELS]).astype(np.float32); self.sal = rr.uniform(.3, 1.0, (n, len(E.DIALS))).astype(np.float32)
        self.flags = np.column_stack([age < 30, age >= 60, self.area == "large city", np.isin(self.area, ["rural area", "small town"]), self.work == "retired", inc / 3, self.caregiver, self.household == "lives alone", np.char.find(self.household, "children") >= 0, self.household == "lives with housemates"]).astype(np.float32)
        self.traits_truth = np.column_stack([self.tech, self.price, self.privacy, self.social, self.time, self.novelty])
    def wmean(self, x, mask=None):
        if mask is None: return float((x * self.wt).sum() / self.wt.sum())
        w = self.wt[mask]; return float((x[mask] * w).sum() / w.sum())
if __name__ == "__main__":
    import time; t = time.time(); p = WorldPopulation(); print(f"{p.n:,} people in {time.time()-t:.1f}s")
    for i, c in enumerate(p.countries):
        m = p.country == i; print(f"{c['name']:14s} median age {np.median(p.age[m]):4.0f} | under $30k {np.mean(p.inc[m]==0):.0%} | big city {np.mean(p.area[m]=='large city'):.0%} | rural {np.mean(np.isin(p.area[m],['small town','rural area'])):.0%} | kids {np.mean(np.char.find(p.household[m],'children')>=0):.0%} | tech {p.tech[m].mean():.2f} price {p.price[m].mean():.2f} time {p.time[m].mean():.2f} novelty {p.novelty[m].mean():.2f}")
